
services:
  tm-service:
    extends:
      file: base.yaml
      service: tm-service
    ports:
      - "9090:8080"
    depends_on:
      - tm-db
      - tm-ke-service
    env_file:
      - path: "./../resources/.env"
        required: true # default
      - path: "./../resources/env/.env.tm"
        required: true # default
    environment:
      #      - KE_REST_ENDPOINT=https://bluebird:WVOvwb3glJIFy0@ke-test-bluebird.apps.bst2.paas.psnc.pl/ke-test-runtime/rest/
      - KE_REST_ENDPOINT=http://tm-ke-service:8280/rest/
  #      - DB_HOST="${PROJECT_NAME}-${DB_HOST}"
    networks:
      - tm-net

  demo-entsoe-service:
    image: "${REGISTRY_APPLICATION}-entsoe-demo:latest"
#    build:
#      dockerfile: ./docker/entsoe-demo/Dockerfile
#      context: ..
#      tags:
#        - "${REGISTRY_APPLICATION}-entsoe-demo:latest"
#        - "${REGISTRY_APPLICATION}-entsoe-demo:${IMAGE_TAG}"
    depends_on:
      - tm-db
      - tm-ke-service
    env_file:
      - path: "./../resources/.env"
        required: true # default
      - path: "./../resources/env/.env.entsoe.demo"
        required: true # default
    environment:
      - KE_REST_ENDPOINT=http://tm-ke-service:8280/rest/
    networks:
      - tm-net
  tm-db:
    image: postgres:alpine3.23
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRES_USER=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASS}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRESQL_DATABASE=${DB_NAME}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - tm-net
  tm-db-adminer:
    #    profiles: [dev, debug, prod]
    #    container_name: tge-db-adminer
    #    container_name: "${PROJECT_NAME}-${DB_HOST}"
    image: adminer:latest
    restart: always
    depends_on:
      - tm-db
    ports:
      - 9199:8080
    networks:
      - tm-net
#    networks:
#      - gnet
#    environment:
#      DOCKER_DEFAULT_PLATFORM: linux/amd64
  tm-ke-service:
    image: ghcr.io/tno/knowledge-engine/smart-connector:1.4.0
    environment:
      KE_RUNTIME_PORT: 8280 # The port that the KE uses to listen for inter-KE-runtime communication.
      #{TODO: set username and password for basic auth}
#      KE_RUNTIME_EXPOSED_URL: http://thisisausername:thisisapassword@bluebird-proxy-service/ke-service
    ports:
      - 8280:8280
    networks:
      - tm-net
networks:
  tm-net:
    driver: bridge