services:
  dt-service:
    #    todo    todo copy dt_ki.py
    image: "${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/tm-local-entsoe-service:latest"
    ports:
      - "11001:8080"
    build:
      dockerfile: ./docker/entsoe-service/Dockerfile
      args:
        REGISTRY_DOMAIN: ${REGISTRY_DOMAIN}
        REGISTRY_PROJECT: ${REGISTRY_PROJECT}
        IMAGE_TAG: ${TM_TAG}
      tags:
        - "${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/local-dt-service:latest"
    depends_on:
      - tm-db
      - tm-service
      - tm-ke-service
    restart: on-failure:5
    env_file:
      - path: ".env"
        required: true
      - path: "./env/.env.dt"
        required: true
    environment:
      - KE_REST_ENDPOINT=http://tm-ke-service:8280/rest/
    networks:
      - tm-net
