knowledge_engine:
  knowledge_base_id: 'https://example.org/ke/smartconnector'
  kb_name: 'FM service'
  kb_description: 'FM service'
  prefixes:
    kb: "${KB_ID}/"
    ubmarket: "https://ubflex.bluebird.eu/market/"
    rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    rdfs: "<http://www.w3.org/2000/01/rdf-schema#>"
    s4ener: "https://saref.etsi.org/saref4ener/"
    time: "http://www.w3.org/2006/time#"
    saref: "https://saref.etsi.org/core/"
  include:
    - "./resources/deployment/ki/dam.yaml"
    - "./resources/deployment/ki/fm.yaml"
  graph_patterns:
    tou-price:
      name: "tou-price"
      description: "Data points for TOU (tou_uri) timeseries. . Used in ANSWER,ASK ."
      prefixes:
        xsd: "http://www.w3.org/2001/XMLSchema#"
        saref: "https://saref.etsi.org/core/"
      required_bindings:
        - "tou_uri"
        - "tm_uri"
      pattern:
        - ' ?tou_uri rdf:type ?ts_type .'
        - ' ?tou_uri s4ener:producedBy ?tm_uri  .'
        - ' ?dp s4ener:belongsToTimeSeries ?tou_uri ; rdf:type s4ener:DataPoint ; saref:hasTimestamp ?ts ;'
        - '   s4ener:hasEffectivePeriod ubmarket:period_15m ; saref:hasResult ?dpr.'
        - ' ubmarket:period_15m time:hasXSDDuration ${ISP_UNIT} .'
        - ' ?dpr saref:hasValue ?value ; saref:isMeasuredIn ubmarket:EURPerMegawattHour  .'
    tou-price-info-filtered:
      name: "tou-price-info-filtered"
      description: "TOU metadata - find TOU timeseries (tou_uri). Used in ANSWER,ASK  . "
      prefixes:
        xsd: "http://www.w3.org/2001/XMLSchema#"
        saref: "https://saref.etsi.org/core/"
        om: "http://www.ontology-of-units-of-measure.org/resource/om-2/"
      required_bindings:
        - "tm_uri"
      pattern:
        - ' ?tou_uri rdf:type ?ts_type .'
        - ' ?tou_uri s4ener:producedBy ?tm_uri .'
        - ' ?tou_uri s4ener:hasUpdateRate ${ISP_UNIT} .'
        - ' ?tou_uri s4ener:hasCreationTime ?time_create .'
        - ' ?tou_uri s4ener:hasEffectivePeriod  ?tou_period_uri .'
        - ' ?tou_period_uri  rdf:type  time:Interval; time:hasXSDDuration ?tou_period .'
        - ' ?ts_interval_uri rdf:type time:Interval; time:hasBeginning ?ts_date_from; time:hasEnd ?ts_date_to .'
        - ' ?tou_uri ubmarket:hasPowerRange  ?power_range .'
        - ' ?power_range s4ener:endOfRange ?power_range_max ; s4ener:startOfRange ?power_range_min . '
        - '	?power_range_max rdf:type saref:PropertyValue ;  saref:isMeasuredIn om:megawatt ; '
        - '       saref:isValueOfProperty s4ener:Power ; saref:hasValue ?max_value .'
        - '	?power_range_min rdf:type saref:PropertyValue ;  saref:isMeasuredIn om:megawatt ; '
        - '     saref:isValueOfProperty s4ener:Power ; saref:hasValue ?min_value .'
    tm-agent:
      name: "tm-agent"
      description: "Information TM. Used in ANSWER,ASK,POST,REACT."
      prefixes:
        xsd: "http://www.w3.org/2001/XMLSchema#"
        foaf: "http://xmlns.com/foaf/0.1/"
      pattern:
        - ' ?tm_uri rdf:type foaf:Agent . '
        - ' ?tm_uri rdf:type ubmarket:MarketAgent. '

