#tou-price:
#  name: "tou-price"
#  description: "Data points for TOU (tou_uri) timeseries. . Used in ANSWER,ASK ."
#  prefixes:
#    xsd: "http://www.w3.org/2001/XMLSchema#"
#    saref: "https://saref.etsi.org/core/"
#  required_bindings:
#    - "tou_uri"
#  pattern:
#    - ' ?tou_uri rdf:type s4ener:TimeSeries .'
#    - ' ?tou_uri s4ener:producedBy kb:service  .'
#    - ' ?dp s4ener:belongsToTimeSeries ?tou_uri ; rdf:type s4ener:DataPoint ; saref:hasTimestamp ?ts ;'
#    - '   s4ener:hasEffectivePeriod ubmarket:period_15m ; saref:hasResult ?dpr.'
#    - ' ubmarket:period_15m time:hasXSDDuration ${ISP_UNIT} .'
#    - ' ?dpr saref:hasValue ?value ; saref:isMeasuredIn ubmarket:EURPerMegawattHour  .'
#tou-price-info-filtered:
#  name: "tou-price-info-filtered"
#  description: "TOU metadata - find TOU timeseries (tou_uri). Used in ANSWER,ASK  . "
#  prefixes:
#    xsd: "http://www.w3.org/2001/XMLSchema#"
#    saref: "https://saref.etsi.org/core/"
#    om: "http://www.ontology-of-units-of-measure.org/resource/om-2/"
#  required_bindings:
#    - "time_create"
#    - "tou_period"
#  pattern:
#    - ' ?tou_uri rdf:type s4ener:TimeSeries .'
#    - ' ?tou_uri s4ener:producedBy kb:service  .'
#    - ' ?tou_uri s4ener:hasUpdateRate ${ISP_UNIT} .'
#    - ' ?tou_uri s4ener:hasCreationTime ?time_create .'
#    - ' ?tou_uri s4ener:hasEffectivePeriod  ?tou_period_uri .'
#    - ' ?tou_period_uri  rdf:type  time:Interval; time:hasXSDDuration ?tou_period .'
#    - ' ?ts_interval_uri rdf:type time:Interval; time:hasBeginning ?ts_date_from; time:hasEnd ?ts_date_to .'
#    - ' ?tou_uri ubmarket:hasPowerRange  ?power_range .'
#    - ' ?power_range s4ener:endOfRange ?power_range_max ; s4ener:startOfRange ?power_range_min . '
#    - '	?power_range_max rdf:type saref:PropertyValue ;  saref:isMeasuredIn om:megawatt ; '
#    - '       saref:isValueOfProperty s4ener:Power ; saref:hasValue ?max_value .'
#    - '	?power_range_min rdf:type saref:PropertyValue ;  saref:isMeasuredIn om:megawatt ; '
#    - '     saref:isValueOfProperty s4ener:Power ; saref:hasValue ?min_value .'
#tm-agent:
#  name: "tm-agent"
#  description: "Information TM. Used in ANSWER,ASK,POST,REACT."
#  prefixes:
#    xsd: "http://www.w3.org/2001/XMLSchema#"
#    foaf: "http://xmlns.com/foaf/0.1/"
#  pattern:
#    - ' kb:service rdf:type foaf:Agent . '
#    - ' kb:service rdf:type ubmarket:MarketAgent. '